format = """
[┌](bold #3BC0F0)$username\
$hostname\
$shlvl\
$jobs\
$directory\
$git_branch\
$git_status\
$git_state\
$package\
$python
[└─](bold #3BC0F0)$character
"""
right_format = """$time"""

[character]
success_symbol = "[λ](bold #3BC0F0)"
error_symbol = "[λ](bold red)"

[time]
disabled = false
style="bold #3BC0F0"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[shlvl]
symbol = " "

[git_status]
conflicted = "[ ](bold red)"
ahead = "$count"
behind = "$count"
diverged = " "
untracked = "[? ](bold yellow)"
modified = "[! ](bold red)"
stashed = "[. ](bold yellow)"
staged = '+ '
renamed = " "
deleted = "[󰧧 ](bold red)"
style = "bold green"
