
format = """
[┌](bold #3BC0F0)$username\
$hostname\
$shlvl\
$jobs\
$directory\
$kubernetes\
$context\
$git_branch\
$git_status\
$git_state\
$package\
$python\
$cmd_duration
[└─](bold #3BC0F0)$character
"""


[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow)'


[character]
success_symbol = "[λ❯](bold #3BC0F0)"
error_symbol = "[λ❯](bold red)"

[time]
disabled = false

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]

symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[git_status]
conflicted = "[ﲅ](bold red)"
ahead = "$count"
behind = "$count"
diverged = ""
untracked = "[?](bold yellow)"
modified = "[!](bold red)"
stashed = "[.](bold yellow)"
staged = '+'
renamed = ""
deleted = "[](bold red)"
style = "bold green"

[kubernetes]
disabled = false
format = 'on [⛵ in $context (\($namespace\))](dimmed green) '
