#!/home/sean/.asdf/shims/python

import sys
import os
from typing import Literal
import arc
import i3ipc

wm = i3ipc.Connection()

Monitors = Literal["primary", "secondary", "laptop"]

serial_map: dict[Monitors, str] = {
    "secondary": "#ASPB6AG1Rq7d",
    "primary": "5SJ72S3",
    "laptop": "Unknown",
}


@arc.command
def backgrounds(monitor_place: Monitors, background: arc.types.FilePath):
    serial_code = serial_map[monitor_place]

    for monitor in wm.get_outputs():
        print(monitor.serial)
        if monitor.serial == serial_code:
            wm.command(f"output {monitor.name} bg {background} fill")
            return


backgrounds()
