#!/usr/bin/python

import os
import subprocess
import sys
import tomllib

appfi = os.path.expanduser("~/.local/bin/appfi")
config_path = os.path.join(os.path.dirname(__file__), "launcher.toml")

with open(config_path, "rb") as f:
    config = tomllib.load(f)


# Replace environment variables in commands
def process_command(cmd):
    return cmd.replace("$appfi", appfi)


options = {value["label"]: key for key, value in config["options"].items()}

with open("/tmp/rofi_launcher.log", "w") as f:
    f.write(str(sys.argv))

if len(sys.argv) > 1:
    option = sys.argv[1]
    if option in options:
        key = options[option]
        command = process_command(config["options"][key]["command"])
        subprocess.run(command, shell=True)
    else:
        print(f"Invalid option: {option}")
        # sys.exit(1)
else:
    # Display options in configured order
    print(
        "\n".join(config["options"][key]["label"] for key in config["display"]["order"])
    )
