[module/alsa]
type = internal/alsa

label-volume = "墳 "
label-volume-foreground = ${root.foreground}

format-muted-foreground = ${colors.foreground-alt}
label-muted = " ﱝ"
format-volume-padding = 2

[module/alsa-ramp]
inherit = module/alsa
format-volume = <ramp-volume> 
ramp-volume-0 = 奄
ramp-volume-1 = 奔
ramp-volume-2 = 墳

[module/alsa-bar]
inherit = module/alsa

format-volume = <label-volume> <bar-volume>

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}
