
[font]
size = 14.0

[font.normal]
family = "SauceCodePro Nerd Font"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Control"

[window.padding]
x = 0
y = 0

[general]
import = ["/home/sean/.config/alacritty/colors.toml"]
