[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x44464d"
blue = "0x676c71"
cyan = "0x8d6e63"
green = "0x27292c"
magenta = "0x9e9e9e"
red = "0xff9800"
white = "0xffffff"
yellow = "0x323639"

[colors.cursor]
cursor = "0x80868b"
text = "0x202124"

[colors.normal]
black = "0x2c2d30"
blue = "0x2196f3"
cyan = "0x00bcd4"
green = "0x00e676"
magenta = "0x673ab7"
red = "0xf44336"
white = "0x80868b"
yellow = "0xffeb3b"

[colors.primary]
background = "0x202124"
foreground = "0x80868b"
