#!/usr/bin/env bash

appfi=$HOME/.local/bin/appfi
pid=`pgrep wf-recorder`
status=$?

if [ $status != 0 ]
then
  echo "Starting recording"
  $appfi run record > /dev/null 2>&1 &
else
  echo "Stopping recording"
  pkill --signal SIGINT wf-recorder > /dev/null 2>&1
fi;
