#!/home/sean/.asdf/shims/python

# Need to use this script to set the config for my monitors because the
# DP port that is used for each monitor is not always the same. It probably depends
# on the order that the monitors are connect to the computer.


import i3ipc

wm = i3ipc.Connection()

serial_map = {
    "#ASPB6AG1Rq7d": "pos 0 0 mode 2560x1440@143.998hz transform 270",
    "5SJ72S3": "pos 1440 419 mode 3440x1440@99.982hz",
}


for monitor in wm.get_outputs():
    print(f"{monitor.name} {monitor.serial} {serial_map.get(monitor.serial)}")
    if args := serial_map.get(monitor.serial):
        wm.command(f"output {monitor.name} {args}")
